# =========================
# %prefix% - player's prefix
# %player% - player's nickname
# %suffix% - player's suffix
# %message% - message content, sent my player
# %chatcolor% - color of player's chat
# =========================
# Languages supported by plugin:
# ru-RU - Russian
# ua-UA - Ukrainian
# en-US - English
# You can make your own by copying, renaming the file and changing messages.
# To switch the language just change the lang parameter below to the name of
# your yml file in /message_lang/ without <.yml> append.
# =========================
lang: "en-US"

chats:
  default:
    style: "%prefix%%player%%suffix%&f » %chatcolor%%message%"

tablist:
  default:
    style: "%prefix%%player%%suffix%"

prefixes:
  default:
    prefix: "&Player &f"

suffixes:
  default:
    suffix: ""

chatcolor:
  default:
    color: "&r"
